classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursos(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }
 
class PeriodoCurso {
    -id : int
    -idCurso :string
    -idPeiodo : int
    -idProfesor : int
    -horario : string
    +asignarProfesor() : void
    +modificarHorario() : void

}

    class Profesor {
        -id: int
        -nombre: string
        -departamento: string
        +asignarCurso(): void
        +editarPerfil(): void
    }

class Periodo {
    -ao : int 
    -nombre : string
    -activo : booleam
    +crearPeriodo() : void
    +cerrarPeriodo() : void

}

    Estudiante "1" --> "*" PeriodoCurso : matriculado en 
    Curso "1" --> "*" Periodo : ofrecido en 
 Periodo "1" --> "*" PeriodoCurso : contiene
 Profesor "1" --> "*" PeriodoCurso : enseña 